import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Landingpage</Link>
        </li>
        <li>
          <Link to="/verifycertificate">VerifyCertificate</Link>
        </li>
        <li>
          <Link to="/certificate">Certificate</Link>
        </li>
        <li>
          <Link to="/issuecertificate">IssueCertificate</Link>
        </li>
        <li>
          <Link to="/issuedcertificate">IssuedCertificate</Link>
        </li>
        <li>
          <Link to="/registerinstitute">RegisterInstitute</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
